# source generated by foxGUIb 0.7

class DialogBox
	def initialize( parent)
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::DialogBox.new(parent){|w|
			@DialogBox=w
			w.wdg_name='DialogBox'
			w.padLeft=10
			w.width=117
			w.padRight=10
			w.shown=true
			w.y=298
			w.height=351
			w.padBottom=10
			w.title="Test"
			w.padTop=10
			w.layoutHints=768
			w.x=390
			FX::ArrowButton.new(@DialogBox){|w|
				@ArrowButton=w
				w.wdg_name='ArrowButton'
				w.width=23
				w.arrowStyle=2097152
				w.arrowSize=15
				w.y=10
				w.height=23
				w.x=10
			}
			FX::Button.new(@DialogBox){|w|
				@Button=w
				w.wdg_name='Button'
				w.font=FX::Font.new.from_s('Parchment|200|400|1|0|0|0').to_FXFont
				w.width=97
				w.buttonButtonStyle=33554432
				w.y=37
				w.height=40
				w.x=10
			}
			FX::CheckButton.new(@DialogBox){|w|
				@CheckButton=w
				w.wdg_name='CheckButton'
				w.checkButtonStyle=33554432
				w.font=FX::Font.new.from_s('Tahoma|80|400|1|0|0|0').to_FXFont
				w.width=93
				w.y=81
				w.height=17
				w.x=10
			}
			FX::ComboBox.new(@DialogBox){|w|
				@ComboBox=w
				w.wdg_name='ComboBox'
				w.text="text"
				w.font=FX::Font.new.from_s('Tahoma|80|400|1|0|0|0').to_FXFont
				w.width=91
				w.numVisible=3
				w.y=102
				w.height=19
				w.comboItems="first\nnext\nlast"
				w.numColumns=10
				w.x=10
			}
			FX::Dial.new(@DialogBox){|w|
				@Dial=w
				w.wdg_name='Dial'
				w.value=81
				w.width=44
				w.y=125
				w.height=16
				w.dialStyle=163840
				w.x=10
			}
			FX::Label.new(@DialogBox){|w|
				@Label=w
				w.wdg_name='Label'
				w.frameStyle=12288
				w.font=FX::Font.new.from_s('Tahoma|80|400|1|0|0|0').to_FXFont
				w.width=36
				w.y=145
				w.height=19
				w.img='Label.png'
				w.x=10
			}
			FX::RadioButton.new(@DialogBox){|w|
				@RadioButton=w
				w.wdg_name='RadioButton'
				w.font=FX::Font.new.from_s('Tahoma|80|400|1|0|0|0').to_FXFont
				w.width=91
				w.y=168
				w.height=17
				w.x=10
			}
			FX::TextField.new(@DialogBox){|w|
				@TextField=w
				w.wdg_name='TextField'
				w.font=FX::Font.new.from_s('Tahoma|80|400|1|0|0|0').to_FXFont
				w.width=76
				w.y=189
				w.height=19
				w.numColumns=10
				w.x=10
				w.justify=0
			}
			FX::ToggleButton.new(@DialogBox){|w|
				@ToggleButton=w
				w.wdg_name='ToggleButton'
				w.frameStyle=24576
				w.font=FX::Font.new.from_s('Tahoma|80|400|1|0|0|0').to_FXFont
				w.width=46
				w.y=212
				w.height=21
				w.state=true
				w.x=10
			}
			FX::Slider.new(@DialogBox){|w|
				@Slider=w
				w.wdg_name='Slider'
				w.value=10
				w.width=97
				w.y=237
				w.height=19
				w.tickDelta=2
				w.sliderStyle=1179648
				w.x=10
			}
			FX::Spinner.new(@DialogBox){|w|
				@Spinner=w
				w.wdg_name='Spinner'
				w.range=-2147483648..2147483647
				w.font=FX::Font.new.from_s('Tahoma|80|400|1|0|0|0').to_FXFont
				w.width=41
				w.y=260
				w.height=19
				w.numColumns=3
				w.x=10
			}
			FX::ProgressBar.new(@DialogBox){|w|
				@ProgressBar=w
				w.wdg_name='ProgressBar'
				w.displayText=true
				w.font=FX::Font.new.from_s('Tahoma|80|400|1|0|0|0').to_FXFont
				w.width=97
				w.progress=33
				w.y=324
				w.height=17
				w.x=10
			}
		}
	end
	attr_reader :topwin
	attr_reader :DialogBox
	attr_reader :ArrowButton
	attr_reader :Button
	attr_reader :CheckButton
	attr_reader :ComboBox
	attr_reader :Dial
	attr_reader :Label
	attr_reader :RadioButton
	attr_reader :TextField
	attr_reader :ToggleButton
	attr_reader :Slider
	attr_reader :Spinner
	attr_reader :ProgressBar
end

#unit test
if __FILE__==$0
	require 'libGUIb16'
	app=FX::App.new
	w=DialogBox.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	app.create
	app.run
end
