# Copyright (c) 2004-2006 by Henon (meinrad dot recheis at gmail dot com)

require 'libGUIb14' if __FILE__ ==$0 #MAKE_DROP
	
class StyleVisitor
	def apply_to( widget, recursive=true)
		widget.recursive{|w|
			identifier="#{w.class.to_s.gsub( /Fox|::|FX/, '')}_style"
			send identifier, w #if respond_to? identifier
			break unless recursive
		}
	end
end

class FlatStyle < StyleVisitor
	attr_accessor :frameColor
	def initialize
		@frameColor=Fox::FXRGB 0,0,0
		@backColor=Fox::FXRGB 230,230,230
	end
	def Button_style w
		w.frameStyle=Fox::FRAME_LINE
		w.hiliteColor=@frameColor
		w.shadowColor=@frameColor
		w.backColor=@backColor
	end
	def TextField_style w
		w.frameStyle=Fox::FRAME_LINE
		w.borderColor=Fox::FXRGB 168,168,168
		#w.shadowColor=@frameColor
	end
	def method_missing(*args)
		identifier, w = args
		unless identifier.to_s =~ /style/
			raise args.join( ",")
		end
		w.backColor=@backColor
	end
end


#unit test
if __FILE__==$0 # MAKE_CUTOFF

	# source generated by foxGUIb 0.5.1
	class DialogBox
		def initialize( parent)
			construct_widget_tree( parent)
			init if respond_to? 'init'
		end
		
		def construct_widget_tree( parent)
			@topwin=
			FX::MainWindow.new(parent){|w|
				@dialogBox=w
				w.wdg_name='dialogBox'
				w.width=500
				w.shown=true
				w.y=552
				w.height=400
				w.x=121
				FX::Label.new(@dialogBox){|w|
					@label=w
					w.wdg_name='label'
					w.width=38
					w.height=19
				}
				FX::TextField.new(@dialogBox){|w|
					@textfield=w
					w.wdg_name='textfield'
					w.width=86
					w.y=23
					w.height=21
					w.numColumns=10
				}
				FX::Button.new(@dialogBox){|w|
					@button=w
					w.wdg_name='button'
					w.width=51
					w.y=48
					w.height=23
				}
				FX::CheckButton.new(@dialogBox){|w|
					@checkbutton=w
					w.wdg_name='checkbutton'
					w.width=103
					w.y=75
					w.height=19
				}
				FX::RadioButton.new(@dialogBox){|w|
					@radiobutton=w
					w.wdg_name='radiobutton'
					w.width=99
					w.y=98
					w.height=19
				}
			}
		end
		attr_reader :topwin
		attr_reader :dialogBox
		attr_reader :label
		attr_reader :textfield
		attr_reader :button
		attr_reader :checkbutton
		attr_reader :radiobutton
	end

	app=FX::App.new
	w=DialogBox.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	FlatStyle.new.apply_to w.topwin
	app.create
	app.run
end