# source generated by foxGUIb 0.5.1

class GenRubyDialog
	def initialize( parent)
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::DialogBox.new(parent){|w|
			@GenRubyDialog=w
			w.wdg_name='GenRubyDialog'
			w.width=367
			w.shown=true
			w.y=408
			w.height=403
			w.decorations=16646144
			w.title="Code Generator Dialog"
			w.x=1065
			FX::Packer.new(@GenRubyDialog){|w|
				@Packer=w
				w.wdg_name='Packer'
				w.backColor=Fox::FXRGBA(230,230,230,255)
				w.padLeft=0
				w.width=367
				w.padRight=0
				w.height=403
				w.shadowColor=Fox::FXRGBA(128,128,128,255)
				FX::Label.new(@Packer){|w|
					@Label=w
					w.wdg_name='Label'
					w.text="Generate Ruby Code:"
					w.backColor=Fox::FXRGBA(183,225,255,255)
					w.padLeft=10
					w.font=FX::Font.new.from_s('Sans|100|0|0|0|0|0').to_FXFont
					w.width=367
					w.height=29
					w.shadowColor=Fox::FXRGBA(128,128,128,255)
					w.padTop=10
					w.layoutHints=1024
					w.justify=32768
				}
				FX::HorizontalSeparator.new(@Packer){|w|
					@HorizontalSeparator=w
					w.wdg_name='HorizontalSeparator'
					w.backColor=Fox::FXRGBA(0,0,0,255)
					w.width=367
					w.separatorStyle=131072
					w.y=29
					w.height=2
					w.padTop=1
				}
				FX::CheckButton.new(@Packer){|w|
					@locked=w
					w.wdg_name='locked'
					w.baseColor=Fox::FXRGBA(230,230,230,255)
					w.text="Lock settings"
					w.backColor=Fox::FXRGBA(230,230,230,255)
					w.width=113
					w.padRight=10
					w.hiliteColor=Fox::FXRGBA(168,168,168,255)
					w.borderColor=Fox::FXRGBA(230,230,230,255)
					w.y=31
					w.height=19
					w.shadowColor=Fox::FXRGBA(168,168,168,255)
					w.layoutHints=4
					w.state=true
					w.boxColor=Fox::FXRGBA(230,230,230,255)
					w.x=254
				}
				FX::GroupBox.new(@Packer){|w|
					@GroupBox3=w
					w.wdg_name='GroupBox3'
					w.text="Starting point:"
					w.backColor=Fox::FXRGBA(230,230,230,255)
					w.padLeft=10
					w.frameStyle=0
					w.width=367
					w.padRight=10
					w.y=50
					w.height=74
					w.shadowColor=Fox::FXRGBA(128,128,128,255)
					w.padBottom=10
					w.padTop=0
					w.vSpacing=2
					w.layoutHints=1024
					FX::HorizontalSeparator.new(@GroupBox3){|w|
						@horizontalseparator2=w
						w.wdg_name='horizontalseparator2'
						w.width=347
						w.separatorStyle=131072
						w.y=19
						w.x=10
					}
					FX::HorizontalFrame.new(@GroupBox3){|w|
						@HorizontalFrame13=w
						w.wdg_name='HorizontalFrame13'
						w.backColor=Fox::FXRGBA(230,230,230,255)
						w.padLeft=4
						w.width=347
						w.padRight=4
						w.y=22
						w.height=42
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.x=10
						FX::GroupBox.new(@HorizontalFrame13){|w|
							@GroupBox11=w
							w.wdg_name='GroupBox11'
							w.text=""
							w.backColor=Fox::FXRGBA(230,230,230,255)
							w.padLeft=0
							w.frameStyle=0
							w.font=FX::Font.new.from_s('Tahoma|80|400|1|0|0|0').to_FXFont
							w.width=122
							w.padRight=0
							w.height=42
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.padBottom=0
							w.padTop=0
							w.x=4
							FX::RadioButton.new(@GroupBox11){|w|
								@topmost=w
								w.wdg_name='topmost'
								w.text="Topmost widget"
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=122
								w.height=19
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.state=true
							}
							FX::RadioButton.new(@GroupBox11){|w|
								@selected=w
								w.wdg_name='selected'
								w.text="Selected widget"
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=122
								w.y=23
								w.height=19
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.state=true
							}
						}
						FX::Label.new(@HorizontalFrame13){|w|
							@node=w
							w.wdg_name='node'
							w.text="root"
							w.backColor=Fox::FXRGBA(230,230,230,255)
							w.padLeft=5
							w.frameStyle=12288
							w.width=38
							w.padRight=5
							w.borderColor=Fox::FXRGBA(139,137,132,255)
							w.y=10
							w.height=21
							w.layoutHints=40
							w.x=215
						}
					}
				}
				FX::HorizontalSeparator.new(@Packer){|w|
					@HorizontalSeparator2=w
					w.wdg_name='HorizontalSeparator2'
					w.backColor=Fox::FXRGBA(230,230,230,255)
					w.width=367
					w.separatorStyle=0
					w.y=124
					w.height=6
					w.padTop=5
				}
				FX::GroupBox.new(@Packer){|w|
					@GroupBox4=w
					w.wdg_name='GroupBox4'
					w.text="Output:"
					w.backColor=Fox::FXRGBA(230,230,230,255)
					w.padLeft=10
					w.frameStyle=0
					w.width=367
					w.padRight=10
					w.y=130
					w.height=103
					w.shadowColor=Fox::FXRGBA(128,128,128,255)
					w.padBottom=10
					w.padTop=0
					w.vSpacing=2
					w.layoutHints=1024
					FX::HorizontalSeparator.new(@GroupBox4){|w|
						@horizontalseparator3=w
						w.wdg_name='horizontalseparator3'
						w.width=347
						w.separatorStyle=131072
						w.y=19
						w.x=10
					}
					FX::RadioButton.new(@GroupBox4){|w|
						@plain=w
						w.wdg_name='plain'
						w.text="Ruby sequence"
						w.backColor=Fox::FXRGBA(230,230,230,255)
						w.padLeft=6
						w.width=122
						w.y=22
						w.height=19
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.state=true
						w.x=10
					}
					FX::RadioButton.new(@GroupBox4){|w|
						@to_class=w
						w.wdg_name='to_class'
						w.text="Ruby class"
						w.backColor=Fox::FXRGBA(230,230,230,255)
						w.padLeft=6
						w.width=92
						w.y=43
						w.height=17
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.padBottom=0
						w.state=true
						w.x=10
					}
					FX::HorizontalSeparator.new(@GroupBox4){|w|
						@horizontalseparator4=w
						w.wdg_name='horizontalseparator4'
						w.backColor=Fox::FXRGBA(230,230,230,255)
						w.padLeft=20
						w.width=347
						w.separatorStyle=131072
						w.shown=false
						w.y=62
						w.height=5
						w.padBottom=4
						w.x=10
					}
					FX::HorizontalFrame.new(@GroupBox4){|w|
						@HorizontalFrame=w
						w.wdg_name='HorizontalFrame'
						w.backColor=Fox::FXRGBA(230,230,230,255)
						w.padLeft=10
						w.width=271
						w.padRight=10
						w.hSpacing=4
						w.y=62
						w.height=31
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.padBottom=10
						w.layoutHints=8
						w.x=48
						FX::Label.new(@HorizontalFrame){|w|
							@Label3=w
							w.wdg_name='Label3'
							w.text="Class name:"
							w.backColor=Fox::FXRGBA(230,230,230,255)
							w.padLeft=0
							w.width=81
							w.height=19
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.padBottom=0
							w.padTop=4
							w.x=10
						}
						FX::TextField.new(@HorizontalFrame){|w|
							@className=w
							w.wdg_name='className'
							w.width=166
							w.hiliteColor=Fox::FXRGBA(128,128,128,255)
							w.height=21
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.numColumns=20
							w.x=95
						}
					}
				}
				FX::Label.new(@Packer){|w|
					@Label33=w
					w.wdg_name='Label33'
					w.text="Write source code to file:"
					w.backColor=Fox::FXRGBA(230,230,230,255)
					w.padLeft=12
					w.width=171
					w.y=233
					w.height=22
					w.padBottom=0
					w.padTop=7
				}
				FX::HorizontalSeparator.new(@Packer){|w|
					@horizontalseparator5=w
					w.wdg_name='horizontalseparator5'
					w.backColor=Fox::FXRGBA(230,230,230,255)
					w.padLeft=10
					w.width=367
					w.padRight=10
					w.separatorStyle=131072
					w.y=255
					w.height=5
					w.padBottom=4
				}
				FX::HorizontalFrame.new(@Packer){|w|
					@HorizontalFrame6=w
					w.wdg_name='HorizontalFrame6'
					w.packingHints=65536
					w.backColor=Fox::FXRGBA(230,230,230,255)
					w.padLeft=4
					w.width=367
					w.padRight=4
					w.y=362
					w.height=41
					w.shadowColor=Fox::FXRGBA(128,128,128,255)
					w.padBottom=10
					w.padTop=10
					w.layoutHints=1025
					FX::Button.new(@HorizontalFrame6){|w|
						@cancel=w
						w.wdg_name='cancel'
						w.text="Cancel"
						w.backColor=Fox::FXRGBA(255,255,168,255)
						w.padLeft=4
						w.frameStyle=12288
						w.width=53
						w.padRight=4
						w.hiliteColor=Fox::FXRGBA(168,168,168,255)
						w.buttonButtonStyle=33554432
						w.y=10
						w.height=21
						w.shadowColor=Fox::FXRGBA(168,168,168,255)
						w.layoutHints=8
						w.x=54
					}
					FX::Button.new(@HorizontalFrame6){|w|
						@to_console=w
						w.wdg_name='to_console'
						w.text="Test"
						w.backColor=Fox::FXRGBA(255,255,168,255)
						w.frameStyle=12288
						w.width=53
						w.hiliteColor=Fox::FXRGBA(168,168,168,255)
						w.buttonButtonStyle=33554432
						w.y=10
						w.height=21
						w.shadowColor=Fox::FXRGBA(168,168,168,255)
						w.x=157
					}
					FX::Button.new(@HorizontalFrame6){|w|
						@OK=w
						w.wdg_name='OK'
						w.text="OK"
						w.backColor=Fox::FXRGBA(255,255,168,255)
						w.padLeft=4
						w.frameStyle=12288
						w.width=53
						w.padRight=4
						w.hiliteColor=Fox::FXRGBA(168,168,168,255)
						w.buttonButtonStyle=33554432
						w.y=10
						w.height=21
						w.shadowColor=Fox::FXRGBA(168,168,168,255)
						w.layoutHints=8
						w.x=260
					}
				}
				FX::HorizontalSeparator.new(@Packer){|w|
					@horizontalseparator13=w
					w.wdg_name='horizontalseparator13'
					w.backColor=Fox::FXRGBA(0,0,0,255)
					w.width=367
					w.separatorStyle=131072
					w.y=360
					w.height=2
					w.padTop=1
					w.layoutHints=1041
				}
			}
		}
	end
	attr_reader :topwin
	attr_reader :GenRubyDialog
	attr_reader :Packer
	attr_reader :Label
	attr_reader :HorizontalSeparator
	attr_reader :locked
	attr_reader :GroupBox3
	attr_reader :horizontalseparator2
	attr_reader :HorizontalFrame13
	attr_reader :GroupBox11
	attr_reader :topmost
	attr_reader :selected
	attr_reader :node
	attr_reader :HorizontalSeparator2
	attr_reader :GroupBox4
	attr_reader :horizontalseparator3
	attr_reader :plain
	attr_reader :to_class
	attr_reader :horizontalseparator4
	attr_reader :HorizontalFrame
	attr_reader :Label3
	attr_reader :className
	attr_reader :Label33
	attr_reader :horizontalseparator5
	attr_reader :HorizontalFrame6
	attr_reader :cancel
	attr_reader :to_console
	attr_reader :OK
	attr_reader :horizontalseparator13
end

#unit test
if __FILE__==$0
	require 'libGUIb14'
	app=FX::App.new
	w=GenRubyDialog.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	app.create
	app.run
end
