# source generated by foxGUIb 0.5.1

class MainWin
	def initialize( parent)
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::MainWindow.new(parent){|w|
			@MainWin=w
			w.wdg_name='MainWin'
			w.width=500
			w.shown=true
			w.y=400
			w.height=400
			w.decorations=16646144
			w.title="foxGUIb v3.0"
			w.x=550
			FX::VerticalFrame.new(@MainWin){|w|
				@container=w
				w.wdg_name='container'
				w.backColor=Fox::FXRGBA(168,168,168,255)
				w.width=500
				w.height=400
				w.shadowColor=Fox::FXRGBA(128,128,128,255)
				w.padBottom=5
				FX::MenuBar.new(@container){|w|
					@Menubar=w
					w.wdg_name='Menubar'
					w.backColor=Fox::FXRGBA(183,225,255,255)
					w.width=500
					w.height=23
					w.shadowColor=Fox::FXRGBA(128,128,128,255)
					FX::MenuTitle.new(@Menubar){|w|
						@main_mt=w
						w.wdg_name='main_mt'
						w.text="Main"
						w.backColor=Fox::FXRGBA(183,225,255,255)
						w.width=42
						w.y=2
						w.height=19
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.x=3
						FX::MenuPane.new(@main_mt){|w|
							@MenuPane=w
							w.wdg_name='MenuPane'
							w.backColor=Fox::FXRGBA(230,230,230,255)
							w.y=82
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.x=117
							FX::MenuCommand.new(@MenuPane){|w|
								@open_project=w
								w.wdg_name='open_project'
								w.text="Change working directory..."
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=2
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuSeparator.new(@MenuPane){|w|
								@MenuSeparator=w
								w.wdg_name='MenuSeparator'
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=22
								w.height=2
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane){|w|
								@new_mainwin=w
								w.wdg_name='new_mainwin'
								w.text="New MainWindow"
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=24
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane){|w|
								@new_dialog=w
								w.wdg_name='new_dialog'
								w.text="New DialogBox"
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=44
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane){|w|
								@open_dialog=w
								w.wdg_name='open_dialog'
								w.text="Open Layout ..."
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=64
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane){|w|
								@save_dialog=w
								w.wdg_name='save_dialog'
								w.text="Save Layout"
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=84
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane){|w|
								@save_dialog_as=w
								w.wdg_name='save_dialog_as'
								w.text="Save Layout As ..."
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=104
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane){|w|
								@close_dialog=w
								w.wdg_name='close_dialog'
								w.text="Close Layout"
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=124
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuSeparator.new(@MenuPane){|w|
								@MenuSeparator2=w
								w.wdg_name='MenuSeparator2'
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=144
								w.height=2
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane){|w|
								@quit=w
								w.wdg_name='quit'
								w.text="Exit"
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=146
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
						}
					}
					FX::MenuTitle.new(@Menubar){|w|
						@build_mt=w
						w.wdg_name='build_mt'
						w.text="CodeGenerator"
						w.backColor=Fox::FXRGBA(183,225,255,255)
						w.width=110
						w.y=2
						w.height=19
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.x=49
						FX::MenuPane.new(@build_mt){|w|
							@MenuPane2=w
							w.wdg_name='MenuPane2'
							w.backColor=Fox::FXRGBA(230,230,230,255)
							w.y=82
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.x=163
							FX::MenuCommand.new(@MenuPane2){|w|
								@genruby=w
								w.wdg_name='genruby'
								w.text="Ruby Generator ..."
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=2
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuSeparator.new(@MenuPane2){|w|
								@MenuSeparator21=w
								w.wdg_name='MenuSeparator21'
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=22
								w.height=2
								w.shadowColor=Fox::FXRGBA(172,168,153,255)
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane2){|w|
								@gencpp=w
								w.wdg_name='gencpp'
								w.text="C++ Generator ..."
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.enabled=false
								w.width=0
								w.selBackColor=Fox::FXRGBA(49,106,197,255)
								w.y=24
								w.height=20
								w.shadowColor=Fox::FXRGBA(172,168,153,255)
								w.x=2
							}
							FX::MenuSeparator.new(@MenuPane2){|w|
								@MenuSeparator22=w
								w.wdg_name='MenuSeparator22'
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=44
								w.height=2
								w.shadowColor=Fox::FXRGBA(172,168,153,255)
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane2){|w|
								@genpy=w
								w.wdg_name='genpy'
								w.text="Python Generator ..."
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.enabled=false
								w.width=0
								w.selBackColor=Fox::FXRGBA(49,106,197,255)
								w.y=46
								w.height=20
								w.shadowColor=Fox::FXRGBA(172,168,153,255)
								w.x=2
							}
							FX::MenuSeparator.new(@MenuPane2){|w|
								@MenuSeparator23=w
								w.wdg_name='MenuSeparator23'
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=66
								w.height=2
								w.shadowColor=Fox::FXRGBA(172,168,153,255)
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane2){|w|
								@geneiffel=w
								w.wdg_name='geneiffel'
								w.text="Eiffel Generator ..."
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.enabled=false
								w.width=0
								w.selBackColor=Fox::FXRGBA(49,106,197,255)
								w.y=68
								w.height=20
								w.shadowColor=Fox::FXRGBA(172,168,153,255)
								w.x=2
							}
							FX::MenuSeparator.new(@MenuPane2){|w|
								@MenuSeparator24=w
								w.wdg_name='MenuSeparator24'
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=88
								w.height=2
								w.shadowColor=Fox::FXRGBA(172,168,153,255)
								w.x=2
							}
						}
					}
					FX::MenuTitle.new(@Menubar){|w|
						@view_mt=w
						w.wdg_name='view_mt'
						w.text="View"
						w.backColor=Fox::FXRGBA(183,225,255,255)
						w.width=41
						w.y=2
						w.height=19
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.x=163
						FX::MenuPane.new(@view_mt){|w|
							@MenuPane38=w
							w.wdg_name='MenuPane38'
							w.backColor=Fox::FXRGBA(230,230,230,255)
							w.y=82
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.x=277
							FX::MenuCommand.new(@MenuPane38){|w|
								@viewEventEditor=w
								w.wdg_name='viewEventEditor'
								w.text="Event Editor"
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=2
								w.height=20
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane38){|w|
								@viewDialog=w
								w.wdg_name='viewDialog'
								w.text="Unhide Layout"
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=22
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
							FX::MenuSeparator.new(@MenuPane38){|w|
								@MenuSeparator115=w
								w.wdg_name='MenuSeparator115'
								w.width=0
								w.y=42
								w.height=2
								w.x=2
							}
							FX::MenuCommand.new(@MenuPane38){|w|
								@viewRubyConsole=w
								w.wdg_name='viewRubyConsole'
								w.text="Ruby Console"
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=44
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
						}
					}
					FX::MenuTitle.new(@Menubar){|w|
						@MenuTitle19=w
						w.wdg_name='MenuTitle19'
						w.text="About"
						w.backColor=Fox::FXRGBA(183,225,255,255)
						w.width=50
						w.y=2
						w.height=19
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.x=208
						FX::MenuPane.new(@MenuTitle19){|w|
							@MenuPane19=w
							w.wdg_name='MenuPane19'
							w.backColor=Fox::FXRGBA(230,230,230,255)
							w.y=82
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.x=322
							FX::MenuCommand.new(@MenuPane19){|w|
								@about=w
								w.wdg_name='about'
								w.text="About foxGUIb..."
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=0
								w.y=2
								w.height=20
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
								w.x=2
							}
						}
					}
				}
				FX::HorizontalFrame.new(@container){|w|
					@head=w
					w.wdg_name='head'
					w.backColor=Fox::FXRGBA(183,225,255,255)
					w.padLeft=4
					w.width=500
					w.padRight=4
					w.y=23
					w.height=4
					w.shadowColor=Fox::FXRGBA(128,128,128,255)
					w.layoutHints=1024
					FX::TabBar.new(@head){|w|
						@project_TabBar=w
						w.wdg_name='project_TabBar'
						w.backColor=Fox::FXRGBA(183,225,255,255)
						w.padLeft=0
						w.current=-1
						w.width=492
						w.height=4
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.padTop=0
						w.x=4
					}
				}
				FX::HorizontalSeparator.new(@container){|w|
					@HorizontalSeparator=w
					w.wdg_name='HorizontalSeparator'
					w.backColor=Fox::FXRGBA(0,0,0,255)
					w.width=500
					w.separatorStyle=131072
					w.y=27
					w.height=2
					w.padTop=1
				}
				FX::HorizontalFrame.new(@container){|w|
					@body=w
					w.wdg_name='body'
					w.backColor=Fox::FXRGBA(255,250,240,255)
					w.width=500
					w.hSpacing=1
					w.y=29
					w.height=366
					w.shadowColor=Fox::FXRGBA(128,128,128,255)
					FX::VerticalFrame.new(@body){|w|
						@tree_Frame=w
						w.wdg_name='tree_Frame'
						w.width=18
						w.height=366
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						FX::Label.new(@tree_Frame){|w|
							@treeheader_L=w
							w.wdg_name='treeheader_L'
							w.text="Widget Tree: (LMB: select, RMB: popup)"
							w.backColor=Fox::FXRGBA(168,168,168,255)
							w.padLeft=5
							w.width=18
							w.height=19
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.layoutHints=1024
							w.justify=32768
						}
						FX::Switcher.new(@tree_Frame){|w|
							@Switcher=w
							w.wdg_name='Switcher'
							w.backColor=Fox::FXRGBA(230,230,230,255)
							w.padLeft=0
							w.width=18
							w.padRight=0
							w.y=19
							w.height=347
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.padBottom=0
							w.padTop=0
							w.layoutHints=3072
						}
					}
					FX::VerticalFrame.new(@body){|w|
						@wdg_Container=w
						w.wdg_name='wdg_Container'
						w.width=299
						w.height=366
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.layoutHints=2048
						w.x=19
						FX::Label.new(@wdg_Container){|w|
							@wdg_header_L=w
							w.wdg_name='wdg_header_L'
							w.text="Widget Selector: (LMB: add after, RMB: popup)"
							w.backColor=Fox::FXRGBA(168,168,168,255)
							w.width=299
							w.height=19
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.layoutHints=1024
							w.justify=32768
						}
						FX::ScrollWindow.new(@wdg_Container){|w|
							@ScrollWindow=w
							w.wdg_name='ScrollWindow'
							w.width=299
							w.y=19
							w.height=347
							w.scrollStyle=229376
							FX::VerticalFrame.new(@ScrollWindow){|w|
								@wdg_Frame=w
								w.wdg_name='wdg_Frame'
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=284
								w.height=347
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
							}
						}
					}
					FX::VerticalFrame.new(@body){|w|
						@prop_Container=w
						w.wdg_name='prop_Container'
						w.width=181
						w.height=366
						w.shadowColor=Fox::FXRGBA(128,128,128,255)
						w.layoutHints=2048
						w.x=319
						FX::Label.new(@prop_Container){|w|
							@prop_header_L=w
							w.wdg_name='prop_header_L'
							w.text="Properties:                           "
							w.backColor=Fox::FXRGBA(168,168,168,255)
							w.width=181
							w.height=19
							w.shadowColor=Fox::FXRGBA(128,128,128,255)
							w.layoutHints=1024
							w.justify=32768
						}
						FX::ScrollWindow.new(@prop_Container){|w|
							@ScrollWindow2=w
							w.wdg_name='ScrollWindow2'
							w.width=181
							w.y=19
							w.height=347
							w.scrollStyle=229376
							FX::VerticalFrame.new(@ScrollWindow2){|w|
								@prop_Frame=w
								w.wdg_name='prop_Frame'
								w.backColor=Fox::FXRGBA(230,230,230,255)
								w.width=166
								w.height=347
								w.shadowColor=Fox::FXRGBA(128,128,128,255)
							}
						}
					}
				}
			}
		}
	end
	attr_reader :topwin
	attr_reader :MainWin
	attr_reader :container
	attr_reader :Menubar
	attr_reader :main_mt
	attr_reader :MenuPane
	attr_reader :open_project
	attr_reader :MenuSeparator
	attr_reader :new_mainwin
	attr_reader :new_dialog
	attr_reader :open_dialog
	attr_reader :save_dialog
	attr_reader :save_dialog_as
	attr_reader :close_dialog
	attr_reader :MenuSeparator2
	attr_reader :quit
	attr_reader :build_mt
	attr_reader :MenuPane2
	attr_reader :genruby
	attr_reader :MenuSeparator21
	attr_reader :gencpp
	attr_reader :MenuSeparator22
	attr_reader :genpy
	attr_reader :MenuSeparator23
	attr_reader :geneiffel
	attr_reader :MenuSeparator24
	attr_reader :view_mt
	attr_reader :MenuPane38
	attr_reader :viewEventEditor
	attr_reader :viewDialog
	attr_reader :MenuSeparator115
	attr_reader :viewRubyConsole
	attr_reader :MenuTitle19
	attr_reader :MenuPane19
	attr_reader :about
	attr_reader :head
	attr_reader :project_TabBar
	attr_reader :HorizontalSeparator
	attr_reader :body
	attr_reader :tree_Frame
	attr_reader :treeheader_L
	attr_reader :Switcher
	attr_reader :wdg_Container
	attr_reader :wdg_header_L
	attr_reader :ScrollWindow
	attr_reader :wdg_Frame
	attr_reader :prop_Container
	attr_reader :prop_header_L
	attr_reader :ScrollWindow2
	attr_reader :prop_Frame
end

#unit test
if __FILE__==$0
	require 'libGUIb14'
	app=FX::App.new
	w=MainWin.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	app.create
	app.run
end
