# source generated by foxGUIb 0.5.0

class GuibEventEditor
	def initialize( parent)
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::DialogBox.new(parent){|w|
			@GuibEventEditor=w
			w.wdg_name='GuibEventEditor'
			w.padLeft=0
			w.width=657
			w.padRight=0
			w.shown=true
			w.y=527
			w.height=490
			w.padBottom=0
			w.title="Event Editor"
			w.padTop=0
			w.x=228
			FX::HorizontalFrame.new(@GuibEventEditor){|w|
				@HorizontalFrame2=w
				w.wdg_name='HorizontalFrame2'
				w.width=657
				w.height=490
				FX::VerticalFrame.new(@HorizontalFrame2){|w|
					@editframe=w
					w.wdg_name='editframe'
					w.width=435
					w.height=490
					FX::HorizontalFrame.new(@editframe){|w|
						@editframeBar=w
						w.wdg_name='editframeBar'
						w.width=435
						w.height=22
						w.layoutHints=1024
						FX::Label.new(@editframeBar){|w|
							@editframeLabel=w
							w.wdg_name='editframeLabel'
							w.text="@widget.connect(SEL_COMMAND){"
							w.backColor=Fox::FXRGBA(183,225,255,255)
							w.width=435
							w.height=22
							w.padTop=5
							w.layoutHints=1024
							w.justify=32768
						}
					}
					FX::HorizontalSeparator.new(@editframe){|w|
						@HorizontalSeparator=w
						w.wdg_name='HorizontalSeparator'
						w.backColor=Fox::FXRGBA(0,0,0,255)
						w.width=435
						w.separatorStyle=131072
						w.y=22
						w.height=2
						w.padTop=1
					}
					FX::VerticalFrame.new(@editframe){|w|
						@VerticalFrame4=w
						w.wdg_name='VerticalFrame4'
						w.backColor=Fox::FXRGBA(230,230,230,255)
						w.padLeft=30
						w.width=435
						w.y=24
						w.height=447
						FX::Text.new(@VerticalFrame4){|w|
							@Text=w
							w.wdg_name='Text'
							w.backColor=Fox::FXRGBA(230,230,230,255)
							w.textTextStyle=33554432
							w.width=405
							w.height=447
							w.x=30
						}
					}
					FX::Label.new(@editframe){|w|
						@editframeLabel2=w
						w.wdg_name='editframeLabel2'
						w.text="}"
						w.backColor=Fox::FXRGBA(230,230,230,255)
						w.width=435
						w.y=471
						w.height=19
						w.layoutHints=1024
						w.justify=32768
					}
				}
				FX::VerticalFrame.new(@HorizontalFrame2){|w|
					@eventsframe=w
					w.wdg_name='eventsframe'
					w.backColor=Fox::FXRGBA(183,225,255,255)
					w.width=222
					w.height=490
					w.x=435
					FX::Label.new(@eventsframe){|w|
						@evframeLabel=w
						w.wdg_name='evframeLabel'
						w.backColor=Fox::FXRGBA(183,225,255,255)
						w.width=222
						w.height=22
						w.padTop=5
						w.layoutHints=1024
						w.justify=32768
					}
					FX::HorizontalSeparator.new(@eventsframe){|w|
						@HorizontalSeparator2=w
						w.wdg_name='HorizontalSeparator2'
						w.backColor=Fox::FXRGBA(0,0,0,255)
						w.width=222
						w.separatorStyle=131072
						w.y=22
						w.height=2
						w.padTop=1
					}
					FX::CheckButton.new(@eventsframe){|w|
						@CheckButton=w
						w.wdg_name='CheckButton'
						w.text="show all events"
						w.backColor=Fox::FXRGBA(168,168,168,255)
						w.width=222
						w.y=24
						w.height=19
						w.layoutHints=1024
						w.state=true
						w.justify=32768
					}
					FX::ScrollWindow.new(@eventsframe){|w|
						@ScrollWindow=w
						w.wdg_name='ScrollWindow'
						w.width=222
						w.y=43
						w.height=447
						FX::VerticalFrame.new(@ScrollWindow){|w|
							@eventList=w
							w.wdg_name='eventList'
							w.backColor=Fox::FXRGBA(168,168,168,255)
							w.width=222
							w.height=447
							w.vSpacing=1
						}
					}
				}
			}
			FX::MenuBar.new(@GuibEventEditor){|w|
				@MenuBar=w
				w.wdg_name='MenuBar'
				w.backColor=Fox::FXRGBA(253,255,111,255)
				w.width=657
				w.y=494
				w.height=4
			}
		}
	end
	attr_reader :topwin
	attr_reader :GuibEventEditor
	attr_reader :HorizontalFrame2
	attr_reader :editframe
	attr_reader :editframeBar
	attr_reader :editframeLabel
	attr_reader :HorizontalSeparator
	attr_reader :VerticalFrame4
	attr_reader :Text
	attr_reader :editframeLabel2
	attr_reader :eventsframe
	attr_reader :evframeLabel
	attr_reader :HorizontalSeparator2
	attr_reader :CheckButton
	attr_reader :ScrollWindow
	attr_reader :eventList
	attr_reader :MenuBar
end

#unit test
if __FILE__==$0
	require 'libGUIb14'
	app=FX::App.new
	w=GuibEventEditor.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	app.create
	app.run
end
