# source generated by  'libGUIb14'

class TextView
	def initialize( parent)
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::DialogBox.new(parent){|w|
			@TextView=w
			w.wdg_name='TextView'
			w.padLeft=0
			w.width=400
			w.padRight=0
			w.shown=true
			w.y=494
			w.height=295
			w.padBottom=0
			w.title="Documentation"
			w.padTop=0
			w.x=152
			FX::VerticalFrame.new(@TextView){|w|
				@VerticalFrame=w
				w.wdg_name='VerticalFrame'
				w.backColor=Fox::FXRGBA(174,225,255,255)
				w.width=400
				w.height=295
				w.padTop=3
				FX::Label.new(@VerticalFrame){|w|
					@heading=w
					w.wdg_name='heading'
					w.backColor=Fox::FXRGBA(183,225,255,255)
					w.padLeft=5
					w.font=FX::Font.new.from_s('Sans|100|0|0|0|0|0').to_FXFont
					w.width=46
					w.padRight=5
					w.y=3
					w.height=21
				}
				FX::HorizontalSeparator.new(@VerticalFrame){|w|
					@HorizontalSeparator=w
					w.wdg_name='HorizontalSeparator'
					w.backColor=Fox::FXRGBA(0,0,0,255)
					w.width=400
					w.separatorStyle=131072
					w.y=24
					w.height=2
					w.padTop=1
				}
				FX::VerticalFrame.new(@VerticalFrame){|w|
					@VerticalFrame2=w
					w.wdg_name='VerticalFrame2'
					w.backColor=Fox::FXRGBA(230,230,230,255)
					w.padLeft=5
					w.width=400
					w.y=26
					w.height=259
					FX::Text.new(@VerticalFrame2){|w|
						@Text=w
						w.wdg_name='Text'
						w.backColor=Fox::FXRGBA(230,230,230,255)
						w.textTextStyle=3145728
						w.width=395
						w.height=259
						w.x=5
					}
				}
				FX::HorizontalFrame.new(@VerticalFrame){|w|
					@HorizontalFrame2=w
					w.wdg_name='HorizontalFrame2'
					w.backColor=Fox::FXRGBA(168,168,168,255)
					w.width=400
					w.y=285
					w.height=10
					w.padTop=10
					w.layoutHints=1024
				}
			}
		}
	end
	attr_reader :topwin
	attr_reader :TextView
	attr_reader :VerticalFrame
	attr_reader :heading
	attr_reader :HorizontalSeparator
	attr_reader :VerticalFrame2
	attr_reader :Text
	attr_reader :HorizontalFrame2
end

#unit test
if __FILE__==$0
	require 'libGUIb14'
	app=App.new
	w=TextView.new app
	w.topwin.show(0)
	app.create
	app.run
end
